export const dummyGuests = [
  {
    id: 1,
    name: "Cahyadi Purnomo",
    empId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022",
    checkInTime: "9.46 PM",
    checkOut: "Nov 4th, 2022",
    checkOutTime: "6.12 PM",
    request: "View Notes",
    room: "Deluxe A - 02",
    status: "Refund",
  },
  {
    id: 2,
    name: "Angela Smith",
    empId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022",
    checkInTime: "9.46 PM",
    checkOut: "Nov 4th, 2022",
    checkOutTime: "6.12 PM",
    request: "View Notes",
    room: "Deluxe A - 02",
    status: "Pending",
  },
  {
    id: 3,
    name: "Hendric Suratman",
    empId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022",
    checkInTime: "9.46 PM",
    checkOut: "Nov 4th, 2022",
    checkOutTime: "6.12 PM",
    request: "View Notes",
    room: "Deluxe A - 02",
    status: "Refund",
  },
  {
    id: 4,
    name: "Jajang Lawrence",
    empId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022",
    checkInTime: "9.46 PM",
    checkOut: "Nov 4th, 2022",
    checkOutTime: "6.12 PM",
    request: "View Notes",
    room: "Deluxe A - 02",
    status: "Booked",
  },
];

export const dummyMenu = [
  {
    id: 1,
    name: "Home Holidays",
    createdAt: "Feb 12th 2026",
    status: "Active",
  },
  {
    id: 2,
    name: "Holidays",
    createdAt: "Feb 12th 2026",
    status: "Active",
  },
  {
    id: 3,
    name: "Honeymoon Package",
    createdAt: "Feb 13th 2026",
    status: "Inactive",
  },
];

export const dummySubMenu = [
  {
    id: 1,
    name: "India Holidays",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 2,
    name: "International Holidays",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 3,
    name: "Domestic Holidays",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 4,
    name: "India on Wheels",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 5,
    name: "Hill Stations",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 6,
    name: "Ayurveda & Yoga Retreats",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
  {
    id: 7,
    name: "Spiritual Tours",
    createdAt: "Feb 14th 2026",
    status: "Active",
  },
];

export const packages = [
  {
    id: "#01234",
    title: "Build Branding Persona for Etza",
    createdAt: "Created on May 7th, 2022",
    deadline: "19/02/2022",
    clientName: "John Doe",
    location: "India",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "#01235",
    title: "Design Travel Website UI",
    createdAt: "Created on June 10th, 2022",
    deadline: "25/03/2022",
    clientName: "David Smith",
    location: "USA",
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "#01236",
    title: "Mobile App Dashboard Design",
    createdAt: "Created on July 15th, 2022",
    deadline: "10/04/2022",
    clientName: "Sarah Lee",
    location: "Canada",
    image:
      "https://images.unsplash.com/photo-1493558103817-58b2924bce98?q=80&w=1600&auto=format&fit=crop",
  },
];

export const ContactList = [
  {
    id: 1,
    firstName: "Prakash",
    lastName: "Kumar",
    email: "prakash.kumar@gmail.com",
    mobile: "+919876543210",
    person: 2,
    plan: "Basic",
    note: "Looking forward to this plan.",
  },
  {
    id: 2,
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul.sharma@gmail.com",
    mobile: "+919812345678",
    person: 4,
    plan: "Premium",
    note: "Please confirm availability.",
  },
  {
    id: 3,
    firstName: "Anita",
    lastName: "Verma",
    email: "anita.verma@gmail.com",
    mobile: "+919845612345",
    person: 1,
    plan: "Standard",
    note: "Need more details about the package.",
  },
  {
    id: 4,
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram.singh@gmail.com",
    mobile: "+919900112233",
    person: 3,
    plan: "Basic",
    note: "Call me in the evening.",
  },
  {
    id: 5,
    firstName: "Sneha",
    lastName: "Reddy",
    email: "sneha.reddy@gmail.com",
    mobile: "+919911223344",
    person: 5,
    plan: "Premium",
    note: "Group booking inquiry.",
  },
];

export const BookingMockData = [
  {
    id: 1,
    fullName: "Prakash Kumar",
    country: "India",
    email: "prakash.kumar@gmail.com",
    phoneCode: "+91",
    mobile: "9876543210",
    seatClass: "Economy",
    person: 2,
    fromTo: "Chennai - Dubai",
    travelDate: "03/15/2026",
    note: "Window seats preferred.",
  },
  {
    id: 2,
    fullName: "Rahul Sharma",
    country: "United Arab Emirates",
    email: "rahul.sharma@gmail.com",
    phoneCode: "+971",
    mobile: "501234567",
    seatClass: "Business",
    person: 1,
    fromTo: "Dubai - London",
    travelDate: "04/02/2026",
    note: "Need wheelchair assistance.",
  },
  {
    id: 3,
    fullName: "Anita Verma",
    country: "Singapore",
    email: "anita.verma@gmail.com",
    phoneCode: "+65",
    mobile: "81234567",
    seatClass: "Premium Economy",
    person: 3,
    fromTo: "Singapore - Mumbai",
    travelDate: "05/10/2026",
    note: "Vegetarian meal required.",
  },
  {
    id: 4,
    fullName: "Vikram Singh",
    country: "India",
    email: "vikram.singh@gmail.com",
    phoneCode: "+91",
    mobile: "9900112233",
    seatClass: "Economy",
    person: 4,
    fromTo: "Delhi - Bangkok",
    travelDate: "06/18/2026",
    note: "Group booking.",
  },
  {
    id: 5,
    fullName: "Sneha Reddy",
    country: "United Kingdom",
    email: "sneha.reddy@gmail.com",
    phoneCode: "+44",
    mobile: "7700123456",
    seatClass: "Business",
    person: 2,
    fromTo: "London - New York",
    travelDate: "07/05/2026",
    note: "Flexible travel dates.",
  },
];


export const flightBookingData = [
  {
    id: 1,
    name: "Prakash Kumar",
    from: "Chennai",
    to: "Dubai",
    date: "15 Mar 2026",
    seatClass: "Economy",
    status: "Confirmed",
  },
  {
    id: 2,
    name: "Rahul Sharma",
    from: "Delhi",
    to: "London",
    date: "02 Apr 2026",
    seatClass: "Business",
    status: "Pending",
  },
  {
    id: 3,
    name: "Anita Verma",
    from: "Mumbai",
    to: "Singapore",
    date: "10 May 2026",
    seatClass: "Premium",
    status: "Cancelled",
  },
  {
    id: 4,
    name: "Vikram Singh",
    from: "Bangalore",
    to: "Bangkok",
    date: "18 Jun 2026",
    seatClass: "Economy",
    status: "Confirmed",
  },
  {
    id: 5,
    name: "Sneha Reddy",
    from: "Hyderabad",
    to: "New York",
    date: "05 Jul 2026",
    seatClass: "Business",
    status: "Pending",
  },
];
